---

# Playbook com exemplo de configuração de interfaces de rede via Ansible
# Desenvolvido por Roger Príncipe

- name: Playbook qu seta um IP
  hosts: clienterhel9.s2linux.local 
  vars:
    network_connections:
      - name: "publica"
        interface_name: "enp7s0"
        type: ethernet
        state: up
        autoconnect: true
        ip:
          auto_gateway: false
          address: "172.16.3.10/16"

      - name: "privada"
        #interface_name: "enp7s0"
        autoconnect: false
        state: down
        ip:
          auto_gateway: false
          address:
            - "192.168.1.10/24"
            - "192.168.1.20/24"

      - name: "bond0"
        interface_name: "bond0"
        type: "bond"
        state: "up"
        autoconnect: true
        bond:
          mode: "active-backup"
          miimon: 1000
        ip:
          auto_gateway: false
          address: "192.44.100.100/24"

      - name: "bond-port1"
        interface_name: "enp9s0"
        type: "ethernet"
        autoconnect: true
        state: "up"
        controller: "bond0"

      - name: "bond-port2"
        interface_name: "enp10s0"
        type: "ethernet"
        autoconnect: true
        state: "up"
        controller: "bond0"

  tasks:
    - name: Seta um IP
      ansible.builtin.include_role:
        name: rhel-system-roles.network
...
