---

- name: Playbook de teste de Magic Variables
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Exibe os hosts do inventário
      ansible.builtin.debug:
        var: groups.all

    - name: Apresentando os servidores
      ansible.builtin.debug:
        msg: "Servidor: {{ item }}"
      loop: groups.all
...
