---

- name: Playbook qu seta um IP
  hosts: postgresql.automation.here
  vars:
    network_connections:
      - name: "{{ nome_perfil }}"
        interface_name: "{{ nome_interface }}"
        state: up
        type: ethernet
        ip:
          address:
            - "172.12.150.22/24"
            - "{{ meu_endereco_ip }}/{{ mascara_cidr }}"

  tasks:
    - name: Seta um IP
      ansible.builtin.include_role:
        name: rhel-system-roles.network
